version: '3'

services:
  api-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=80
    networks:
      - mynet
    ports:
      - 80:80

  stream-receiver:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - WS_HOST=api-server
      - WS_PORT=80
    networks:
      - mynet
    depends_on:
      - api-server
    command: python3 -m app.stream_receiver
    
networks:
  dbnet:
