version: '3'

services:
  db:
    image: redis
    restart: always
    networks:
      - dbnet
    ports: 
      - 6379:6379

  api-server:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - dbnet
    ports:
      - 80:80
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - dbnet
    depends_on:
      - db
    command: rq worker --url redis://db:6379

  stream-receiver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - dbnet
    depends_on:
      - db
      - api-server
    command: python3 -m app.stream_receiver

networks:
  dbnet:
