version: '3'

services:
  db:
    image: redis
    restart: always
    networks:
      - dbnet
    ports: 
      - 6379:6379

  api-server:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./app:/code/app
    networks:
      - dbnet
    ports:
      - 80:80
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: dev.Dockerfile
    networks:
      - dbnet
    depends_on:
      - db
    command: rq worker --url redis://db:6379

networks:
  dbnet: