services:
  api-server:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./app:/code/app

  worker:
    build:
      context: .
      dockerfile: dev.Dockerfile

  stream-receiver:
    build:
      context: .
      dockerfile: dev.Dockerfile